# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: "mysql:5.7"
    ports:
      - '3309:3306'
    environment:
       - MYSQL_USER=root
       - MYSQL_PASSWORD=1234
       - MYSQL_DATABASE=gonvo
       - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - my-datavolume:/var/lib/mysql
  php:
    image: devilbox/php-fpm:5.6-work
    volumes:
      - ./:/code

volumes:
  my-datavolume:
